src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;

use Doctrine\ORM\Mapping as Record;

use Symfony\Component\String\Slugger\AsciiSlugger;

/**
 * @Record\Entity(repositoryClass=ArticleRepository::class)
*/
class Article
{
	/**
	 * @Record\Id()
	 * @Record\GeneratedValue()
	 * @Record\Column(type="integer")
	 */
	private $id;
	
	/**
	 * @Record\Column(type="string", length=255)
	 */
	private $title;
	
	/**
	 * @Record\Column(type="text")
	 */
	private $content;
	
	/**
	 * @Record\Column(type="string", length=255)
	 */
	private $cover;
	
	/**
	 * @Record\Column(type="string", length=19)
	 */
	private $creation_date;
	
	public function __construct()
	{
		$this->creation_date = (new \DateTime('now'))->format('Y-m-d H:i:s');
	}

	public function getId(): ?int
	{
		return $this->id;
	}
	
	public function getTitle(): ?string
	{
		return $this->title;
	}
	
	public function getContent(): ?string
	{
		return $this->content;
	}
	
	public function getCover(): ?string
	{
		return $this->cover;
	}
	
	public function getCreationDate(): ?string
	{
		return $this->creation_date;
	}

	public function getSlug(): string
    {
    	return $this->getId() . '-' . (new AsciiSlugger())->slug($this->getTitle());
    }
		
	public function setTitle(string $title)
	{
		$this->title = $title;
	}
	
	public function setContent(string $content)
	{
		$this->content = $content;
	}
	
	public function setCover(string $cover)
	{
		$this->cover = $cover;
	}
	
	public function setCreationDate(string $date)
	{
		$this->creation_date = $date;
	}
};

?>

templates/admin_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}SpaceBlog - Page d'administration{% endblock %}

{% block body %}

<section class="management">

<a href="/"><button class="main-button">Retour</button></a>

<h2>Page d'administration</h2>

<a href="admin/new"><button class="main-button">Créer un article</button></a>

<ul>
{% for article in articles %}
<li>
	<div class="article-management">
		<h3>{{ article.title }}</h3>
		<p>{{ article.content | raw }}</p>

		<div class="admin-buttons">
		<a href="admin/edit/{{ article.slug }}"><button class="edit-button">Editer</button></a>
		<a href="admin/delete/{{ article.slug }}"><button class="delete-button">Supprimer</button></a>
		</div>
	</div>
</li>
{% endfor %}
</ul>

</section>

{% endblock %}

templates/article_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}SpaceBlog - {{ article.title }}{% endblock %}

{% block body %}

<a href="/"><button class="main-button">Retour</button></a>

<article>
	<img src="/images/covers/{{ article.cover }}" alt="{{ article.title }}" />
	<h1>{{ article.title }}</h1>
	<p>{{ article.content | raw }}</p>
	<h6>Publié {{ article.creationDate }}</h6>
</article>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
<title>{% block title %}SpaceBlog{% endblock %}</title>

{{ encore_entry_link_tags('app') }}
</head>

<body>

{% include 'header.html.twig' %}

<main id="main-page">
{% block body %}
{% endblock %}
</main>

{% include 'footer.html.twig' %}

<script>
{% block scripts %}

{{ encore_entry_link_tags('app') }}

{% endblock %}
</script>

</body>

</html>

templates/editor_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}SpaceBlog - Editeur d'article{% endblock %}

{% block body %}

<a href="/admin"><button class="main-button">Retour</button></a>

{{ form(form) }}

{% endblock %}

{% block scripts %}

var article_content = document.getElementById('article_content');

article_content.style.height = article_content.scrollHeight + 'px';

article_content.addEventListener('keydown', function(e) {
	article_content.style.height = article_content.scrollHeight + 'px';
});

{% endblock %}

templates/footer.html.twig
<footer>
<div id="footer-logo">
	<img class="logo-img" src="{{ asset('/images/spaceblog_logo_2.png') }}" alt="SpaceBlog Logo" />
	<h3 class="logo-title">SpaceBlog</h3>
</div>
</footer>

templates/header.html.twig
<header>
<div id="header-logo">
	<img class="logo-img" src="{{ asset('images/spaceblog_logo_1.png') }}" alt="SpaceBlog Logo" />
	<h3 class="logo-title">SpaceBlog</h3>
</div>
</header>

templates/home_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}SpaceBlog - Page d'accueil{% endblock %}

{% block body %}

<div id="banner">
	<img id="banner-image" src="{{ asset('images/spaceship.png') }}" alt="Spaceship" />
	<figcaption id="banner-title">Découvrez <span class="orange-text">l'espace</span> comme jamais auparavant</figcaption>
</div>

<h2>Nos articles</h2>
<section class="summaries">

{% for article in articles %}
<a href="article/{{ article.slug }}">
<div class="article-summary">
	<img src="/images/covers/{{ article.cover }}" alt="{{ article.title }}" />
	<div class="summary-title"><h3 class="article-title">{{ article.title }}</h3></div>
</div>
</a>
{% endfor %}
	
</section>

{% block scripts %}

<script>
</script>

{% endblock %}

{% endblock %}